### ISSUE TITLE
连续跑了100w行之后就坏了

### ISSUE THREAD

**Issue by LRY1994** [fxsjy/jieba#1008]
s = jieba.cut(s, cut_all=False)
后面都是输出一个字一个字，重新再跑就可以

![image](https://github.com/fxsjy/jieba/assets/17881352/8e3bd520-db76-4722-869b-80c05af15688)
![image](https://github.com/fxsjy/jieba/assets/17881352/8589296f-80f8-4dd7-8dbb-f9d56cbaff77)

**Comment by manother** [comment]
邮件已收到~

**Comment by LRY1994** [comment]
不好意思，是自己处理的问题，关了
