### ISSUE TITLE
网址、英文、数字和中文混合的语料，网站和英文也分词

### ISSUE THREAD

**Issue by cloga** [fxsjy/jieba#12]
语料中有网址的话，会分出http这样的词，而实际上这个是网址，如果网址中包含数字字母的随机数，也会分出来。
http://t.cn/zjARTkg
[u'http', u't', u'cn', u'zjARTkg']
https://github.com/fxsjy/jieba/issues/new
[u'https', u'github', u'com', u'fxsjy', u'jieba', u'issues', u'new']
我不清楚这个是不是应该我在给jieba原始语料中就应该去掉URL，还是应该包含在模块中

**Comment by Beeder** [comment]
jieba最新版修改了
```
re_skip_default = re.compile("(\r\n|\s|:|/)", re.U)
```
但是还是把URL分割开了，求问怎么修改。
另外在进行微博分词的时候，怎样才能不把`@`单独切开呢？

**Comment by gumblex** [comment]
我现在用这个：
```python
def atfix(self, text):
    at = False
    for t in jieba.cut(text):
        if t == '@':
            at = True
        elif at:
            yield '@' + t
            at = False
        else:
            yield t
```

**Comment by Beeder** [comment]
这样虽然能切出@微博昵称，但是怎样不把url切开呢？

**Comment by gumblex** [comment]
你需要先用正则预处理文本，把不需要分词的先排除，上面的例子仅适用于英文用户名。URL 的正则可以参考 https://mathiasbynens.be/demo/url-regex

**Comment by Beeder** [comment]
谢谢，不过好像NLPIR比jieba方便，能自动切@微博昵称 和URL。

**Comment by ma47** [comment]
一直在用jieba，但是追着楼上的咨询一下：中文的分词哪个比较好用些？jieba相比较于其它分词工具的优势在哪里？
抱歉本人不是这方面的专家，对工具的使用基本上都是“拿来主义”，也没有专业能力对这个问题有自己的看法，谢谢！

**Comment by ma47** [comment]
还是非常感谢作者，给我们这些门外汉提供了好用的工具！


2015-09-24 11:44 GMT-04:00 Ji Ma <ma47@umail.iu.edu>:

> 一直在用jieba，但是追着楼上的咨询一下：中文的分词哪个比较好用些？jieba相比较于其它分词工具的优势在哪里？
> 抱歉本人不是这方面的专家，对工具的使用基本上都是“拿来主义”，也没有专业能力对这个问题有自己的看法，谢谢！
>
>
