### ISSUE TITLE
jieba词性标注采用的标注集合？

### ISSUE THREAD

**Issue by hitalex** [fxsjy/jieba#155]
jieba的文档上说，“采用和ictclas兼容的标记法”，但是我没有找到ictclass的词性集合，有没有人提供以下？

**Comment by wybert** [comment]
http://wenku.baidu.com/view/72b03002eff9aef8941e068e.html

**Comment by anderscui** [comment]
这个也挺清晰的：https://gist.github.com/luw2007/6016931
