### ISSUE TITLE
词性标注问题

### ISSUE THREAD

**Issue by ericxsun** [fxsjy/jieba#218]
我数据里的“有点”全部被标注成“/n”了。

服务/vn 有点/n 情调/n

这是怎么了？要怎么处理下才行？

谢谢。

**Comment by fxsjy** [comment]
@followyourheart , 为了兼顾性能， dict.txt中的词只有一种词性，只有对于dict.txt中没有的词才会调用HMM去识别。你可以删掉dict.txt中的这行：`有点 3706 n ` 或者，你改一下dict.txt中它的词性。
