### ISSUE TITLE
Broken package in pypi 

### ISSUE THREAD

**Issue by vetal4444** [fxsjy/jieba#250]
$ easy_install jieba

    ValueError: bad marshal data (unknown type code)

It seems there are some *.pyc files in package, so we get this error.

Python 3.4

    $ easy_install --version
    setuptools 15.0

**Comment by fxsjy** [comment]
I installed pytho3.4 on my windows laptop, and found the installation with pypi work well.

C:\Users\sunjunyi01>c:\Python34\Scripts\pip3.4.exe install jieba
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting jieba
  Downloading jieba-0.36.1.zip (7.4MB)
    100% |################################| 7.4MB 61kB/s
Installing collected packages: jieba
  Running setup.py install for jieba
Successfully installed jieba-0.36.1


I am not sure if your problem can be reproduced on Linux. And, I will have a try later.

**Comment by vetal4444** [comment]
pip install package without any problems. They are only under easy_install. The trouble is when we set jieba in setup.py requirements list of our package and run:

    setup.py install

we will get an exception :(

**Comment by fxsjy** [comment]
@vetal4444 , sorry for that. 
Currently, I am busy working on other projects. I make a new version(0.36.2), which remove the *.pyc files. You can try : easy_install -U jieba to have a look.

**Comment by vetal4444** [comment]
I think we can close this issue.
Thanks for quick response and resolve this :+1:

**Comment by jiji879** [comment]
newspaper3k 依赖 jieba3k，安装时也报了这个错，看了下 jieba3k-0.35.1 仍然有 pyc 文件
