### ISSUE TITLE
TextRank算法结果没有过滤停止词?

### ISSUE THREAD

**Issue by Stumble** [fxsjy/jieba#258]
我在不少文章上进行了测试,大部分情况下, Textrank算法的效果不错, 但是在某些情况下, Textrank算法会导出大量的停止词. 我还没读那篇paper, 所以具体原因也不是很明白.

提供一个样例:

<pre>
text = """
2015全球移动互联网大会期间，专注人机交互解决方案的Synaptics公司在北京举行了媒体见面会，Synaptics独立触控业务部副总裁Brian Daly在会后接受了媒体采访，作为唯一一名受邀出席的自媒体人，我有幸与Brian Daly就指纹识别技术、网络信息安全、智能汽车等领域交换了各自的看法。 Brian Daly在演讲中提到了触控技术为人机交互带来的变革，以及未来人机交互的发展趋势。其中从按键到触屏的转变是交互方式变革的关键，生物识别、情境识别以及全方位感知技术将在未来应用与各种硬件设备和现实生活场景中，而传统的人机交互方式将逐渐退出历史舞台。 一个十分有趣的现象是，从年龄上看比我们更早接触触屏设备的儿童，在使用触屏手机、平板电脑等产品后，会误认为电视机、电冰箱的屏幕同样支持触摸操作，当他的指令得不到设备反馈是，他会认为这台设备是坏的。这一现象或许可以说明传统的人机交互技术已经无法满足人们的生活需求，而在智能家居、可穿戴设备、智能汽车等领域，触控技术仍大有可为。 Synaptics公司总裁兼首席执行官 Rick Bergman向观众演示了触控技术为智能汽车提供的人机交互解决方案。汽车的前窗玻璃成了一块儿可触摸操作的屏幕，在行驶过程中驾驶员可点击屏幕图标进行导航、查询路况等操作，不过对于直接关系到人身安全的汽车而言，人们依然有许多不安和疑惑，比如如何避免误操作？Brian Daly在采访中表示不同功能会配合不同的震动频率以确保触控的准确性。 除了在更多设备和生活场景中的应用外，人们对触控技术的需求还体现在操作的灵敏程度和操作前的预览功能上。比如，带着手套也能实现触控。在滑雪、打高尔夫、开车等生活场景中用户需要带手套，触控技术的创新将能够满足用户在这方面的需求。另外在手指潮湿或干燥的情况下，同样也能够实现触控。第三是能够在用户做出选择前进行预览，比如绽放图片和地图。 有媒体记者提问：“为什么我的iPhone屏幕在沾到水的情况下无法触控？”Brian Daly笑道：“那是因为iPhone没有采用Synaptics的解决方案。” Synaptics除了为各大OEM厂商提供人机交互解决方案外，还有一个身份是“FIDO联盟”的核心成员。该联盟是一个制定生物识别认证系统标准的国际联盟，其口号是“杀死密码”。不过，我对FIDO这一宏伟的目标表示质疑，Brian Daly在这一问题上的表现出的诚恳让我感到敬佩。以下是对话实录： ME：Brian Daly先生，关于指纹识别技术，我有两个问题，一个小问题，一个大问题。小问题是我对FIDO提出的“杀死密码”的口号有些疑虑，我认为在未来很长一段时间内指纹识别技术仍然无法得以普及，最乐观的情况是与密码方式并存。因为你无法回避一些相对极端的案例，比如我的手指受伤了、烧伤了、蜕皮了等情况，如果我完全使用指纹识别的话，将无法访问我所有的账户和设备。不知道您对我的观点怎么看？ Brian Daly：我同意生物识别技术包括指纹识别技术确实在今后一段时间内将会与传统密码技术共存的。因为即便是手指太干（或太湿）的情况下，触控技术都会受到影响，更别说受伤和蜕皮的情况了。所以必须要有另外一些不同的生物身份识别的方式作为补充，比如面部识别、虹膜识别，甚至是个人签字也可以，还有各种不同的方法来帮助你，一种方法不行了，马上转到另外一个。另外密码识别的方法还是一种非常好的备份。 ME：继续刚才的问题。我的大问题是，我们知道网络安全问题目前已经上升到国家战略层面，Synaptics的触控技术，特别是指纹识别技术是一项涉及到用户隐私数据的技术，而FIDO结合Synaptics指纹识别技术将要制定的生物识别认证系统国际标准，在与不同国家政府间的合作的过程中会否因为信息安全问题遭到阻力？同时作为一个成立于美国的联盟，FIDO如何证明它的独立性？ Brian Daly：这个确实牵扯的方面太多了，作为一家公司或者一个联盟的成员，我们应该以全球化的思维方式来思考问题，我们确实跟世界各国政府和地区都有合作，而网络安全问题对我们而言确实也是一个挑战。但对Synaptics公司来讲，我们在这方面是有优势的，我们不仅面向全球，我们在世界各国本地都有很多本地化的工作。在中国我们业务量就非常大，我们跟中国政府和一些企业部门也合作得非常好。 ME：刚才在会场看到Rick演示的人机交互技术在智能汽车上的应用，我感到很惊讶。我们知道人是经常犯错误的，但人是不允许机器犯错的，特别是汽车这种直接关系到人生命安全的交通工具，所以人们对安全的担忧，会不会使得这项更前卫的人机交互技术，包括现在的无人驾驶技术推行起来有很大的阻力？ Brian Daly：关于您提到的无人驾驶汽车，我认为还处在非常早的发展时期。但是美国确实已经出现这种无人驾驶车，横跨美国行驶过。虽然能做到这样，美国只有少量几个州允许无人驾驶汽车能够上路行驶。很多州是不允许车上没人的，必须有一个司机控制这个车。但是我认为这项技术早晚还会被真正采用，但现在还是早期。目前已经有这样的技术，比如汽车可以在你的车逼近另外一个车之前自动感知到，能够帮助你自动制动、刹车。我认为你刚才讲的无人驾驶汽车这个技术，还要花很多年才能真正得到市场的采用。 ME：刚才Rick分享了人机交互技术的四次变革，其中有一个是情境识别，我不是特别理解，能否举一个简单典型的例子，或者现在已经应用到了一些设备上的案例？ Brian Daly：我可以举个例子，比如现在在美国很多用户都使用过Google now这个应用，它可以知道你的地点，我一到北京这个软件就知道我已经从美国到了中国北京了，附近有一个水族中心等等，水立方那儿不是有个水族中心吗，它会识别你可能到中国会有旅游的需求，就马上推出一些新的建议和想法，比如在周围应该看一些什么景点。或者到了该吃饭的时间，手机就感知到我现在在什么位置，就告诉我在北京什么区域，这些地方有些什么样的饭馆，给你提一些建议。还有比如我在美国要赶飞机，手机就感知到了我要坐飞机，而且知道机场在什么地方，而且还知道我现在在什么位置上，还知道交通堵不堵。如果堵的话，会提醒我早点走。如果飞机延误了，它会提前告诉我你不用着急那么走了。这些就是情境感知的应用。作者微信：375952010，扫一扫关注作者公众号。
"""

rtn = jieba.analyse.textrank(text)
print (text)
rtn2 = jieba.analyse.extract_tags(text)
type(rtn)
print (','.join(rtn))
print (','.join(rtn2))
</pre>

结果:
技术,是,到,会,有,识别,比如,汽车,人机交互,触控

触控,Daly,Brian,技术,人机交互,Synaptics,指纹识别,识别,FIDO,汽车,比如,无人驾驶,ME,设备,感知,问题,一个,密码,我们,Rick

**Comment by gumblex** [comment]
TF-IDF [有过滤](https://github.com/fxsjy/jieba/blob/master/jieba/analyse/__init__.py#L89)，Textrank 没过滤。
