### ISSUE TITLE
目前有没有人在做.NET版本的jieba？

### ISSUE THREAD

**Issue by anderscui** [fxsjy/jieba#259]
这段时间jieba用下来很喜欢，然后也看到目前已经有多种其它不同语言的移植版本，想知道有没有在做.NET版本？如果没有的话，我想尝试做一下:)

**Comment by fxsjy** [comment]
@anderscui ， 据我所知还没有。

**Comment by anderscui** [comment]
@fxsjy 嗯，那我就试一下，主要是学习一下jieba的代码和算法:)

**Comment by anderscui** [comment]
@fxsjy ，https://github.com/anderscui/jieba.NET，目前分词功能已经基本完成，cut、cut_for_search与jieba一致，会继续优化。其它功能慢慢添加。

**Comment by a9261** [comment]
你也有在做@o@ 要互相支援一下嗎？ 我還在對照python版寫呢 :dancer:

**Comment by anderscui** [comment]
@a9261 太巧了，到现在已经完成主要的功能了：分词、词性和关键词。接下来会添加更多的test case，重构代码，优化性能等等，一起讨论讨论：）

**Comment by a9261** [comment]
有什麼需要幫忙的可以一起研究研究 :D

**Comment by anderscui** [comment]
@a9261 已加。
