### ISSUE TITLE
jieba.posseg.cut结果中词性为'i'是什么？

### ISSUE THREAD

**Issue by hiericzhu** [fxsjy/jieba#265]
请问用jieba.posseg.cut词性标注后，词性显示为i的是什么词？
('让', 'v'), ('我们', 'r'), ('拭目以待', 'i'), ('。', 'x')

《中科院ICTPOS3.0汉语词性标记集.doc》里面并没有标记为'i'的词。

这个'i'就是字典里面定义的，是什么分类呢？
谢谢。

**Comment by gumblex** [comment]
参见这个：https://gist.github.com/luw2007/6016931

i	成语	取英语成语idiom的第1个字母。

**Comment by hiericzhu** [comment]
查了默认字典里面标记为i的词，发现有些不能算成语，比如“鸣不平”。
请问词典是用什么标准标记的？有些标记在《中科院ICTPOS3.0汉语词性标记集.doc》里面没有。
另外这个链接打不开，请检查一下，谢谢。

        Line 344259: 鸡鸣而起 3 i
	Line 344260: 鸡鸣起舞 3 i
	Line 344263: 鸡鸭鱼肉 3 i
	Line 344276: 鸣不平 16 i
	Line 344277: 鸣乎哀哉 3 i
	Line 344309: 鸣谢碑 3 i
	Line 344318: 鸣钟食鼎 3 i

**Comment by hiericzhu** [comment]
原来是墙的问题打不开那个网页，谢谢。
