### ISSUE TITLE
加载自定义字典抛出异常

### ISSUE THREAD

**Issue by Linusp** [fxsjy/jieba#274]
基本代码如下:
```python
jieba.load_userdict("./math_dict.txt")
```

出错信息为:
> Building prefix dict from /usr/local/lib/python2.7/dist-packages/jieba/dict.txt ...
> Loading model from cache /tmp/jieba.cache
> Dumping model to file cache /tmp/jieba.cache
> Dump cache file failed.
> Traceback (most recent call last):
> File "/usr/local/lib/python2.7/dist-packages/jieba/\_\_init\_\_.py", line 100, in initialize
>    replace_file(fpath, cache_file)
> OSError: [Errno 1] Operation not permitted

原因是加载了我自定义的字典后会去尝试覆盖 /tmp/jieba.cache，因为是在服务器上，有其他用户在我之前用过 jieba ，导致我没有权限修改 /tmp/jieba.cache 这个文件。试过修改 jieba.tmp_dir ，不过好像没什么作用，不过返回了一个不同的异常:
> Building prefix dict from /home/xxx/venv/local/lib/python2.7/site-packages/jieba/dict.txt ...
> Dumping model to file cache /home/xxx/venv/local/lib/python2.7/site-packages/jieba/jieba.cache
> Dump cache file failed.
> Traceback (most recent call last):
>   File "/home/xxx/venv/local/lib/python2.7/site-packages/jieba/\_\_init\_\_.py", line 106, in initialize
>     replace_file(fpath, cache_file)
> OSError: [Errno 18] Invalid cross-device link

[README](https://github.com/fxsjy/jieba#载入词典) 里提到的 `jieba.dt` 我也没有找到。虽然报了这个错也还能继续运行下去，不过还是希望有一个完整的解决办法。

版本: 0.36.2

**Comment by gumblex** [comment]
GitHub 上的开发版的接口做了调整，把大部分全局函数用类做了包装。
0.36.2 指定缓存文件夹用 `jieba.tmp_dir`
开发版手工指定缓存文件夹用 `jieba.dt.tmp_dir`，指定缓存文件名用 `jieba.dt.cache_file`。
第二个异常 #275 修复了。

**Comment by Linusp** [comment]
@gumblex 我是用 pip 安装的，每次都有这个问题，这个 fix 只在开发版上有效?

**Comment by gumblex** [comment]
对，要等到 @fxsjy 更新 PyPI 上的版本。你可以直接使用这里的开发版。

**Comment by fxsjy** [comment]
@gumblex , Done.

**Comment by Linusp** [comment]
@fxsjy Thanks!

**Comment by digoal** [comment]
0.37有同样的问题
Building prefix dict from /usr/lib/python2.6/site-packages/jieba-0.37-py2.6.egg/jieba/dict.txt ...
Loading model from cache /tmp/jieba.cache
Dumping model to file cache /tmp/jieba.cache
Dump cache file failed.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/jieba-0.37-py2.6.egg/jieba/__init__.py", line 146, in initialize
    _replace_file(fpath, cache_file)
OSError: [Errno 1] Operation not permitted
Loading model cost 1.399 seconds.
Prefix dict has been built succesfully.

**Comment by fxsjy** [comment]
@digoal ，自定义临时目录：jieba.dt.tmp_dir后，仍然有问题？

**Comment by Linusp** [comment]
@digoal 0.37 用 jieba.dt.tmp_dir 设置 cache 文件目录后再 load_user_dict ，我这边这样做是不会有问题的

**Comment by digoal** [comment]
是权限问题，现在好了，因为我开始用ROOT用户，自动在tmp下创建了一个cache文件，后面用普通报错。
