### ISSUE TITLE
能够在Tokinize函数的基础上实现词性标注吗？

### ISSUE THREAD

**Issue by denglizong** [fxsjy/jieba#281]
如题。Tokinize()函数能显示分词结果在文中的位置，对后续文本处理非常使用。想请教能否在此基础上实现词性标注的整合？ 也就是对于每一行，实现如下输出：
word 永和                start: 0                end:2         n
word 服装                start: 2                end:4         n
word 饰品                start: 4                end:6         n
word 有限公司            start: 6                end:10    n

还请各位牛人帮助。谢谢大家！

**Comment by gumblex** [comment]
```python
import jieba.posseg

def postokenize(sentence, HMM=True):
    """Tokenize a sentence and yields tuples of (word, start, end, pos)"""
    p = 0
    for word, pos in jieba.posseg.cut(sentence, HMM=HMM):
        width = len(word)
        yield (word, p, p + width, pos)
        p += width
```

**Comment by denglizong** [comment]
Dear gumblex, 
         It works! Thank you very much! @gumblex

**Comment by denglizong** [comment]
@gumblex : Dear gumblex: Thanks for your guidance！ I've developed a function named postokenize() which also support "search" model based on your work. I sincerely appreciated for your kindness. Best wishes~
