### ISSUE TITLE
并行分词问题

### ISSUE THREAD

**Issue by bluedesire** [fxsjy/jieba#284]
如果一个程序中，多个线程调用jieba分词，是否会自动启用多个jieba分词的进程？还是阻塞式，一个一个线程共用一个分词进程？

**Comment by gumblex** [comment]
不会自动启动多个进程，是开多个分词线程，阻塞是由于 GIL 导致。

**Comment by gumblex** [comment]
不会自动启动多个进程，是开多个分词线程，阻塞是由于 GIL 导致。
