### ISSUE TITLE
如何同时使用多个分词器实例？

### ISSUE THREAD

**Issue by Gwill** [fxsjy/jieba#290]
文档中的使用方法都是全局式的，请问如何生成多个配置不同的分词器实例可供同时处理不同的语料？

**Comment by gumblex** [comment]
`jieba.Tokenizer([dictionary])`，用法和全局一样；全局分词器也是一个实例 `jieba.dt`。
在 `initialize` 之前可以改 `tmp_dir`, `cache_file` 属性来更改缓存文件位置。

**Comment by Gwill** [comment]
那么 `t = jieba.Tokenizer([dictionary]) ` 生成的实例，如何使用 `jieba.analyse` 相关功能呢？比如 `jieba.analyse.set_stop_words(file_name)`

**Comment by gumblex** [comment]
`jieba.analyse` 有 `TFIDF` 和 `TextRank` 类，也可以生成多实例，默认实例是 `default_tfidf`, `default_textrank`。更改这些实例的 `tokenizer` 和 `postokenizer` 为新的分词器实例即可。`set_stop_words` 也是作用在这些实例上的。
注意 textrank 以及 tfidf 的词性过滤功能需要 `postokenizer`。可以用 `jieba.posseg.POSTokenizer(tokenizer)` 生成以指定 Tokenizer 为基础的词性分词器。

**Comment by Gwill** [comment]
嗯，多谢，明白了，不过感觉这样的封装结构不是很好，可以改进，可以更加 OO 一点。

**Comment by struggleToDawn** [comment]
使用多个分词器实例 后不能用并行分词功能了。 这样怎么办呢？

**Comment by jinjiajia** [comment]
t= jieba.Tokenizer()
t.load_userdict(keywordspath)
postokenizer=jieba.posseg.POSTokenizer(tokenizer=t)
t3=jieba.analyse.TFIDF()
请问我怎么更改jieba.analyse实例的 tokenizer 和 postokenizer 为新的分词器实例呢？
