### ISSUE TITLE
python3 版本的没有标点符号

### ISSUE THREAD

**Issue by Axure** [fxsjy/jieba#295]
jieba.cut 和 jieba.posseg.cut 都不输出标点符号。python2 的没有这个问题。

**Comment by Axure** [comment]
似乎不是 dict.txt 的差异。

**Comment by gumblex** [comment]
我没发现过这样的问题。

**Comment by Axure** [comment]
是我在 python2 中的编码不正确，导致句子没有按照标点符号分裂。不是 jieba 的问题。
