### ISSUE TITLE
如何将'湖南长沙市'分开

### ISSUE THREAD

**Issue by fangxingli** [fxsjy/jieba#297]
jieba.suggest_freq(('湖南', '长沙市'), True)
print ' '.join(jieba.cut('湖南长沙市天心区', HMM=False))

还是返回 ----湖南长沙市 天心区
我希望得到的是 -----湖南 长沙市 天心区

**Comment by fairsky66** [comment]
将 湖南 长沙市 分别放入你的用户词典

**Comment by yanyiwu** [comment]
@fairsky66 这个不可以吧？

**Comment by gumblex** [comment]
@yanyiwu 应该可以，没有写词频就调用 suggest_freq

**Comment by anderscui** [comment]
也可以使用del_word

**Comment by fairsky66** [comment]
@yanyiwu 必然可以
比如：
湖南 10000
长沙市 10

当然，最好别这么调词频。使用@gumblex 的建议
