### ISSUE TITLE
自定义词典userdict使用遇到问题,求助

### ISSUE THREAD

**Issue by cnchenji** [fxsjy/jieba#305]
按照作者的方法，自作了与作者例子中一样的自定义字典。 但是运行的时候出现错误提示。

  File "D:\Anaconda\lib\site-packages\jieba-0.37-py2.7.egg\jieba\__init__.py", line 381, in load_userdict
    f.name, lineno, line))

UnboundLocalError: local variable 'line' referenced before assignment

不知道是不是有其他朋友也遇到过类似问题。

**Comment by gumblex** [comment]
用户字典应为 UTF-8 编码。
365 行 UTF-8 解码失败，然后错误处理的时候没有定义 line。
在 #307 修正后可以通过例如 `jieba.load_userdict(codecs.open('userdict.txt', 'r', encoding='gbk'))` (Python 2) 来载入其他编码的文件。

**Comment by cnchenji** [comment]
非常感谢，问题已解决，；）
