### ISSUE TITLE
自定义词典文件中的新增词词性被识别为x

### ISSUE THREAD

**Issue by perchouli** [fxsjy/jieba#31]
e.g

```
江西德兴幼儿园唱红歌迎十八大

江西/ns 德兴/ns 幼儿园/nr 唱/v 红歌/x 迎/v 十八大/x
```

自定义词典中的被识别为x，其实应该是n。
1. 自定义字典中可否加入词性？例如 `十八大 5 x`的形式；
2. 如果不行，可以自己编辑原字典吗？（我用vi直接编辑字典dict.txt会导致无法使用)。

**Comment by geogeqq** [comment]
@fxsjy , 所以通过AddWord接口，加入自定义词典，词性设置无效？最后出来全为X？
