### ISSUE TITLE
用SIGHAN Bakeoff 2005测试工具测试得分低

### ISSUE THREAD

**Issue by huchhong** [fxsjy/jieba#340]
我想比较一下结巴分词和其他分词器的效果。使用了SIGHAN Bakeoff 2005测试工具。

我使用测试集里微软研究院提供的词典，再将该词典转换成结巴分词里的词典规则（词后加上词频，没有词性），然后用这个词典替换了结巴分词里的dict.txt。同时测试之前删除了缓存/tmp/jieba.cache。

然后开始测试，得到的得分是：
召回率： 89.9%
准确率： 87%
F值：     88.4%

这个分数应该是比较差的，我再三确认了以上的操作，确认结巴分词使用的是我提供的词典。能否给个解释，为什么得分这么低？我猜测是否是结巴分词里除了dict.txt提供的词典，还有一些其他训练来源？

**Comment by gumblex** [comment]
对，默认使用了 HMM 模型来增加未登录词的识别。我重复了以上实验，得分相同。

如果去掉该 HMM 模型，得分是：
召回率：95.4%
准确率：87.9%
F值：91.5%

这其中 jieba 没有识别全角数字和英文，比如 `２０００年`、`ｉｎｔｅｒｎｅｔ` 等词都把单个字符分开。

**Comment by huchhong** [comment]
我也试了一下，确实是HMM的影响。那么HMM真的有必要吗，从这个结果推断出，HMM在语料库和测试集的词集相对吻合时，会起适得其反的结果。

**Comment by gumblex** [comment]
可以试试自己训练这个 HMM 模型，不过作者没有放出训练脚本。
我通常在实际使用中关掉 HMM。

**Comment by yanyiwu** [comment]
线上使用通常关掉HMM +1
