### ISSUE TITLE
del_word()删词有问题

### ISSUE THREAD

**Issue by yuk1n** [fxsjy/jieba#350]
句子：疯狂动物城   分词结果 ['疯狂', '动物', '城']
我用add_word('动物城', 'abc')添加词后 结果为 [' 疯狂', '动物城']
再用del_word('动物城') 删词后 结果不变 还是 ['疯狂','动物城'] 词性还是我的自定义词性
我用的版本为 0.38

再问一个问题 
我需要文本的词性标注和词语的位置，必须要把同一文本分析两次吗
@fxsjy 
谢谢！

>>> jieba.suggest_freq(('今天', '天气'), True)
0
>>> jieba.lcut(s)
['今天天气', '不错']
这个也有问题 不能切开

**Comment by cavonchen** [comment]
现在最新的0.38版本就差这点没发布，请发明人尽快发布~
