### ISSUE TITLE
能不能只使用自定义字典来分词

### ISSUE THREAD

**Issue by fbikillcia** [fxsjy/jieba#352]
文字为“新浪娱乐讯 3月14日白色情人节，小浪和不少同行们收到了吴奇隆[微博]和刘诗诗[微博]大婚的鲜花伴手礼，正在分享他们的喜悦时”，我只想按照我自定义字典分出来“吴奇隆”“刘诗诗”，应该怎么做？现在的分词结果是“新浪/娱乐讯/ /3/月/14/日白色/情人节/，/小浪/和/不少/同行们/收到/了/吴奇隆/[/微博/]/和/刘诗/诗/[/微博/]/大婚/的/鲜花伴/手礼/，/正/在/分享/他们/的/喜悦时/”。

**Comment by 1354092549** [comment]
可以通过jieba.set_dictionary修改主词典目录达到目的
参考[延迟加载机制](https://github.com/fxsjy/jieba#延迟加载机制)

**Comment by fbikillcia** [comment]
感谢回答！试过了， 不行， 我使用jieba.set_dictionary只放一条记录， 照样还是分出好多词来，您可以试一下。

**Comment by 1354092549** [comment]
对于无法再继续拆分的词，会将单个字作为词对待，包含在列表中

自定义词典文件需要注意，必须用UTF-8编码，且必须不带BOM，如果带BOM，会导致第一行的词语被误识别

对于不在词典中的词，结巴分词采用了HMM模型和Viterbi算法识别
您的需求需要关闭HMM
具体请看github上的readme

代码：
```python
import jieba
jieba.set_dictionary("D:/1.txt")
jieba.initialize()
print(jieba.lcut("长江大桥是中国的一座桥"))
print(jieba.lcut("长江大桥是中国的一座桥",HMM=False))
```
输出（已删除结巴分词加载词库时的输出信息）：
```
['长江', '大桥', '是', '中国', '的', '一座', '桥']
['长江', '大', '桥', '是', '中', '国', '的', '一', '座', '桥']
```

词典内容（UTF-8无BOM编码）：
```
长江 9999
```

**Comment by fbikillcia** [comment]
感谢！
