### ISSUE TITLE
是否有词性标注结果 英文缩写的对应表

### ISSUE THREAD

**Issue by fangpin** [fxsjy/jieba#391]
是否有词性标注结果 英文缩写的对应表.如名词,副词,动词等

**Comment by lujin77** [comment]
我是找的这个做参照：http://blog.csdn.net/syani/article/details/52276282

**Comment by fangpin** [comment]
@lujin77 感谢

**Comment by bedlate** [comment]
same as https://github.com/fxsjy/jieba/issues/411 and https://github.com/fxsjy/jieba/issues/453

see: https://gist.github.com/luw2007/6016931
