### ISSUE TITLE
标点符号和空格的切分现在解决了吗？

### ISSUE THREAD

**Issue by cdj0311** [fxsjy/jieba#396]
我的词典里有一些词是包含标点符号和空格的，比如“宝马(进口)”, "奥迪 A4L"需要连在一起切分，jieba现在解决这个问题了吗？

**Comment by qiaofei32** [comment]
@cdj0311  http://www.wid.org.cn/data/science/player/competition/detail/description/237(基于视角的领域情感分析)?哈哈

**Comment by vkjuju** [comment]
@cdj0311 , @fxsjy , 請問您有找到解決方式嗎?

**Comment by cdj0311** [comment]
@vkjuju 修改__init__里面的正则表达式就可以了

**Comment by vkjuju** [comment]
@cdj0311 但兩個英文字中間有空白的还是不行
