### ISSUE TITLE
在关键字提取中withWeight返回的是权重值，如何返回关键字的词频

### ISSUE THREAD

**Issue by xiaomiba0904** [fxsjy/jieba#402]
withWeight返回的是权重值，如何返回关键字的词频，计数？
虽然可以通过先分词，再通过关键词计数，但希望直接在
jieba.analyse.extract_tags(sentence, topK=20, withWeight=False, allowPOS=()) 函数中
返回关键词出现的次数

**Comment by ruijh** [comment]
TF*IDF
