### ISSUE TITLE
jieba.cut 和 jieba.posseg.cut 分词结果不一致

### ISSUE THREAD

**Issue by baobao7766** [fxsjy/jieba#417]
您好，使用您的分词时遇到了如下情况：

![image](https://cloud.githubusercontent.com/assets/10491686/20952813/0d141920-bc6a-11e6-9ee2-66522d41505a.png)

两个分词用的不适同一个词典，还是说add_dict只能添加jieba.cut中的单词

**Comment by rockyzhengwu** [comment]
我看了jieba的源码，这样不一致的结果是因为这两个方法确实就是不一样的。虽然原理都一样，先使用词典，然后HMM新词发现。但是posseg.cut 方法的HMM的模型是结合了词性的，意思是分词和词性在一个HMM里面。标签是(B,v) 这样的，第一个是分词的标签，第二个是词性的标签，合起来作为HMM模型的状态。

**Comment by AloneGu** [comment]
posseg有没有办法支持cut_all啊

**Comment by yoke88** [comment]
**posseg,cut 能否先用Jieba.cut 先分词，然后对分词结果标记词性啊**，目前也遇到这个问题。

用cut 加载自定义字典可以分正确，但是词性标注时，就变成这样了，无论怎么用自定义字典。

``` python
x='实习生刘柯帆'
jieba.posseg.lcut(x)

# Result
 pair('实习生', 'x'),
 pair('刘珂', 'nrfg'),
 pair('帆', 'n'),
 pair('、', 'x'),
```

**Comment by Ethan-Xia** [comment]
同求此问题的解决方法。

**Comment by ston1992** [comment]
e

**Comment by baobao7766** [comment]
jieba里面HMM这个参数默认貌似为True，这里会有一个新词发现的功能，导致一些加入词典后也分不出来，未加入词典的反而能分出来，也会有词汇量大时分词速度较慢的问题，建议在自己有明确的词典的时候，将HMM设置为False
![image](https://user-images.githubusercontent.com/10491686/38796776-04520440-418f-11e8-84c4-f698f511220d.png)

**Comment by wuyongdec** [comment]
如果要建立一个新词库，先用HMM=TRUE，发现新词？

**Comment by baobao7766** [comment]
@wuyongdec 感觉这个不是很准，如果要建立新词库，这个可能只能做参考，然后靠人工
