### ISSUE TITLE
jieba命令行问题

### ISSUE THREAD

**Issue by yuquanle** [fxsjy/jieba#441]
我在ubuntu使用python -m jieba a.txt > b.txt几秒就分好的词，但是我想用空格作为间隔。于是python -m jieba -d a.txt > b.txt，没有报错，但是几分钟也没分出来。麻烦大神帮我看一下，是我命令输错了还是什么原因。不甚感激！

**Comment by gumblex** [comment]
python -m jieba -d ' ' a.txt > b.txt

**Comment by yuquanle** [comment]
非常感谢 @gumblex
