### ISSUE TITLE
分词功能不正确

### ISSUE THREAD

**Issue by cjliux** [fxsjy/jieba#487]
In [3]: print('/'.join(jieba.cut('「台中」正确应该不会被切开', HMM=False)))
Building prefix dict from /home/cjliux/.local_install/jieba-0.36/jieba/dict.txt ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.189035177231 seconds.
Prefix dict has been built succesfully.
「/台/中/」/正确/应该/不会/被/切开

**Comment by cjliux** [comment]
貌似是因为我没改辞典

**Comment by hongfuli** [comment]
把 “台中” 加入到自定义词典中吧
