### ISSUE TITLE
mac 下 python3 的命令行分词中，选项中加了分割符选项却不指定的话，程序不会自动结束。

### ISSUE THREAD

**Issue by HughWen** [fxsjy/jieba#488]
如图，结巴加载后不会往下执行，而是停在最后一行。
(py3env1) ➜  nlpTest python -m jieba -d cutTest.txt > cuted2.txt
Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/fv/9t0ldhvx03j4ch64rv3j9qh40000gn/T/jieba.cache
Loading model cost 0.855 seconds.
Prefix dict has been built succesfully.

**Comment by Mao-KU** [comment]
cat cutTest.txt | python -m jieba -d > cuted2.txt
这样似乎可以
