### ISSUE TITLE
AttributeError: 'int' object has no attribute 'decode'

### ISSUE THREAD

**Issue by swordspoet** [fxsjy/jieba#502]
![image](https://user-images.githubusercontent.com/14816130/28869155-6ba6512e-77ae-11e7-9bec-743868b1b13f.png)

上图是我的数据前一部分，我的目的是对 titles 一列进行分词，分词的代码如下。现在遇到的问题是`AttributeError: 'int' object has no attribute 'decode'`，所以我认为是 titles 中有 int 所致，所以添加了一个判断条件，但是代码执行的结果依旧是报之前的错。请问这是什么原因？

```python
def jiebait(text):
    seglist = jieba.cut(text, cut_all = True)
    fenci = []
    for word in seglist:
        if (not isinstance(word, int)) and (len(word) >= 2):
            fenci.append(word)
    # 如用搜索引擎模式：
    #seglist = jieba.cut_for_search(text)
    return ' '.join(fenci)
```

![image](https://user-images.githubusercontent.com/14816130/28869122-501c2910-77ae-11e7-8eb6-e4543497a81d.png)

**Comment by chmx0929** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-16-8512cd55213b> in <module>()
      2     result_line = ""
      3     # segment
----> 4     seg_list = [str(w) for w in jieba.cut(line, cut_all = False)]
      5     # remove special character
      6     temp = re.sub("[\s+\.\!_,$%^*(+\"\')]+|[+——()?【】“”！，。？、~@#￥%……&*（）]+", "",("/".join(seg_list)))

<ipython-input-16-8512cd55213b> in <listcomp>(.0)
      2     result_line = ""
      3     # segment
----> 4     seg_list = [str(w) for w in jieba.cut(line, cut_all = False)]
      5     # remove special character
      6     temp = re.sub("[\s+\.\!_,$%^*(+\"\')]+|[+——()?【】“”！，。？、~@#￥%……&*（）]+", "",("/".join(seg_list)))

D:\Anaconda\lib\site-packages\jieba\__init__.py in cut(self, sentence, cut_all, HMM)
    280             - HMM: Whether to use the Hidden Markov Model.
    281         '''
--> 282         sentence = strdecode(sentence)
    283 
    284         if cut_all:

D:\Anaconda\lib\site-packages\jieba\_compat.py in strdecode(sentence)
     35     if not isinstance(sentence, text_type):
     36         try:
---> 37             sentence = sentence.decode('utf-8')
     38         except UnicodeDecodeError:
     39             sentence = sentence.decode('gbk', 'ignore')

AttributeError: 'int' object has no attribute 'decode'

**Comment by gumblex** [comment]
你的 text 本身是不是 int

**Comment by chmx0929** [comment]
本身是int，使用str(w)转成string

**Comment by chmx0929** [comment]
是的，本身是int，但是seg_list = [str(w) for w in jieba.cut(line, cut_all = False)]这一步，应该都转成string了

**Comment by chmx0929** [comment]
解决了 我这边数据转码的问题 不好意思。。。感谢

**Comment by codelover-dev** [comment]
> 解决了 我这边数据转码的问题 不好意思。。。感谢

大佬, 如何解决的呢? 可否说的详细点呢?

**Comment by hanabai** [comment]
> 解决了 我这边数据转码的问题 不好意思。。。感谢

怎么解决的

**Comment by jay-on-zwc** [comment]
修改dataframe的数据类型为string，```df.astype(str)```
