### ISSUE TITLE
调整词典不生效

### ISSUE THREAD

**Issue by zhugw** [fxsjy/jieba#507]
如下所示

```
>>> print('/'.join(jieba.cut('价格便宜')))
价格便宜
```
默认字典中是这样定义的 确实存在一个价格便宜
```
cat dict.txt | grep -e '^价格 ' -e '^便宜 ' -e '价格便宜'
价格 11762 n
价格便宜 4 n
便宜 2013 a
```
而我想要分成： `价格/便宜` 参照调整词典中的介绍 试了下面的方法 均不成功

```
# 删除掉价格便宜 还是一个整体
>>> jieba.del_word('价格便宜')
>>> print('/'.join(jieba.cut('价格便宜')))
价格便宜

# 调节词频 也不起作用
>>> jieba.suggest_freq(('价格', '便宜'), True)
0
>>> print('/'.join(jieba.cut('价格便宜')))
价格便宜
```

所以说现在不知道该怎么做 才能使得正确拆分？

类似的还有`反应速度快` ==》`反应/速度快`
```
>>> print('/'.join(jieba.cut('反应速度快')))
反应速度快
```

**Comment by hanwanhe** [comment]
pip install安装的版本有问题，看 jieba/__init__.py的403行左右，最新的代码是：
freq = int(freq) if freq is not None else self.suggest_freq(word, False)
但是你通过pip install安装的代码是：
freq = int(freq) if freq  else self.suggest_freq(word, False)

造成的结果就是：del_word的时候，没法把词的词频设为0
