### ISSUE TITLE
del_word 无效

### ISSUE THREAD

**Issue by weiczhu** [fxsjy/jieba#509]
def add_word(self, word, freq=None, tag=None):
        """
        Add a word to dictionary.

        freq and tag can be omitted, freq defaults to be a calculated value
        that ensures the word can be cut out.
        """
        self.check_initialized()
        word = strdecode(word)

#下面这段代码在 del_word 的时候有问题，因为del_word 传了一个 freq=0, if 条件为 false，然后走else去取 sugguest_freq 造成 freq 又被赋值为sugguest_freq，结果就是 删除 word无效
        freq = int(freq) if freq else self.suggest_freq(word, False)
#尝试下列修改能解决该问题
        freq = int(freq) if freq is not None else self.suggest_freq(word, False)

        self.FREQ[word] = freq
        self.total += freq
        if tag:
            self.user_word_tag_tab[word] = tag
        for ch in xrange(len(word)):
            wfrag = word[:ch + 1]
            if wfrag not in self.FREQ:
                self.FREQ[wfrag] = 0

    def del_word(self, word):
        """
        Convenient function for deleting a word.
        """
        self.add_word(word, 0)

**Comment by weiczhu** [comment]
PS： 出错版本 jieba-0.3.8

**Comment by zhugw** [comment]
这个问题在最新的代码中已经修改了 见 https://github.com/fxsjy/jieba/blob/master/jieba/__init__.py

**Comment by fxsjy** [comment]
0.39版已经修复

**Comment by xiabofei** [comment]
今天也发现这个bug了，发现已经有同学提交先了O(∩_∩)O~
