### ISSUE TITLE
很赞怎么就拆不开呢

### ISSUE THREAD

**Issue by zhugw** [fxsjy/jieba#512]
`很赞`怎么就拆不开呢？

```
print('/'.join(jieba.cut('手机样式很赞')))
手机/样式/很赞

>>> jieba.get_FREQ('很')
69103
>>> jieba.get_FREQ('赞')
1347
>>> jieba.get_FREQ('很赞')
>>>

```
明明都没有`很赞`这个词啊？ 怎样才能才能将其拆开来呢？ 试了下面的方法 并未生效

```
>>> jieba.del_word('很赞')
>>> jieba.get_FREQ('很赞')
0
>>> print('/'.join(jieba.cut('手机样式很赞')))
手机/样式/很赞
```

另外为什么Python2.7中 `get_FREQ`没有输出呢
```
>>> jieba.get_FREQ('很')
>>> jieba.get_FREQ('赞')
>>> jieba.get_FREQ('很赞')
```

**Comment by fxsjy** [comment]
试试0.39版，用del_word强制拆开。

**Comment by zhugw** [comment]
```
pip install jieba --upgrade
>>> print('/'.join(jieba.cut('手机样式很赞')))
手机/样式/很赞

>>> jieba.del_word('很赞')

>>> print('/'.join(jieba.cut('手机样式很赞')))
手机/样式/很/赞
```

但是还是不明白 明明没有`很赞`这个词 为什么还需要显式del呢？ 如果是`价格便宜`需要显式删除我可以理解
```
Python3
>>> jieba.get_FREQ('价格便宜')
4

Python2.7
>>> jieba.get_FREQ('价格便宜')
>>>
```
奇怪 怎么Python2.7中`get_FREQ`没有输出呢？

**Comment by fxsjy** [comment]
因为jieba默认会对词典里不存在的词做识别，根据单字成词能力猜测。如果你要禁用，传入HMM=False即可

**Comment by guotong1988** [comment]
HMM=False和True最大区别是啥啊

**Comment by jiakechong1991** [comment]
应该是对未登录词是否开启HMM分词

**Comment by kevinhuang06** [comment]
我关闭了HMM还是有case无法拆分。
```
    s = '北京华宇腾飞工贸有限公司'
    for ss in jieba.cut(s, HMM=False):
          print ss,

   # 输出结果
   北京华 宇 腾飞 工贸 有限公司 
```
确认过, 字典中已经没有北京华

**Comment by baiziyuandyufei** [comment]
添加个华宇有吗？




发自网易邮箱大师


在2018年06月28日 19:34，kevinhuang06<notifications@github.com> 写道：

我关闭了HMM还是有case无法拆分。

    s = '北京华宇腾飞工贸有限公司'
    for ss in jieba.cut(s, HMM=False):
          print ss,

   # 输出结果
   北京华 宇 腾飞 工贸 有限公司 


确认过, 字典中已经没有北京华

**Comment by kevinhuang06** [comment]
@baiziyuandyufei 添加华宇是可以的。
HMM关闭以后，不就不会识别新词了吗？为什么还是会把"北京"和"华" 放在一起呢？

**Comment by guotong1988** [comment]
https://github.com/Rokid/better_jieba
