### ISSUE TITLE
支持划分成每个字吗？

### ISSUE THREAD

**Issue by tianjipeng** [fxsjy/jieba#532]
假如有个句子，“我爱天安门”，能否划分成以下几个：我，爱，天，安，门，天安门？就是句子的每个字都划分开在加上词组

**Comment by Mindzy** [comment]
自己写呗，Utf-8编码格式下，每3个字节（一个汉字）append到一个list里就行了，后面再加上分词的词组

**Comment by tianjipeng** [comment]
谢谢
