### ISSUE TITLE
silent flag for initialize

### ISSUE THREAD

**Issue by kerrickstaley** [fxsjy/jieba#569]
The `initialize` function prints out some extra information:
```
>>> import jieba; jieba.initialize()
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.508 seconds.
Prefix dict has been built succesfully.
>>> 
```
It would be nice to have a way to silence this output, for example:
```
>>> import jieba; jieba.initialize(silent=True)
>>>
```
----
`initialize()`很吵:
```
>>> import jieba; jieba.initialize()
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.508 seconds.
Prefix dict has been built succesfully.
>>> 
```
请加一个选择让它安静一点，比如：
```
>>> import jieba; jieba.initialize(silent=True)
>>>
```

**Comment by kerrickstaley** [comment]
I figured out how to fix this using `setLogLevel`:
```
In [1]: import jieba

In [2]: import logging

In [3]: jieba.setLogLevel(logging.ERROR)

In [4]: jieba.initialize()

In [5]: 
```

Closing.

**Comment by Destaq** [comment]
> I figured out how to fix this using `setLogLevel`:
> 
> ```
> In [1]: import jieba
> 
> In [2]: import logging
> 
> In [3]: jieba.setLogLevel(logging.ERROR)
> 
> In [4]: jieba.initialize()
> 
> In [5]: 
> ```

A more concise way of doing this that doesn't require the `logging` module import:
```python
import jieba

jieba.setLogLevel(20)
```
