### ISSUE TITLE
句子分割

### ISSUE THREAD

**Issue by windweller** [fxsjy/jieba#575]
打扰一下，想请问Jieba库能否做句子分割呢？
举个例子，这段对话：
”史卡肯表示:「我今天打的和当初在温布登打的一样,除了这一次幸运之神落在我这边以外。」他说:「其实在温布登时最后的胜利也有可能属于我,因为当时打到了第五盘却仍然僵持在二十比十八的对峙。」菲利普西斯在当初的温布登比赛中,在面对史卡肯时曾经发出四十四个爱司球,但是为他搏得「重炮手」美誉的发球,并没有在今天的球赛中助他一臂之力。菲利普西斯在第一盘第七局以三十比四十落后时,竟然击出双发失误;另外在第九局他又再度犯下双发失误球,让史卡肯得以坐拥两次的破发点,并且顺利赢得第一盘。在这场历时六十六分钟的比赛里,史卡肯表示:「我大力主攻他的第二发球,同时我也对他的第一发球施压,使我取得更多的机会。」这也是史卡肯和菲利普西斯在六度对峙中的第二次获胜。”

看得出来是好几句句子，但是“。”在引号内也有出现，所以不方便直接用“。”去分割。
请问Jieba可以在这种情况下用吗？

如果不行的话，有中文的分句工具吗？

**Comment by Silencezjl** [comment]
看这行代码，https://github.com/fxsjy/jieba/blob/master/jieba/__init__.py#L296
jieba是默认提取出中文来做分词的，按标点split的，具体说是按照这个正则来分的re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._%]+)", re.U)

**Comment by windweller** [comment]
啊，明白了，谢谢：）

**Comment by gumblex** [comment]
```
import re
resentencesp = re.compile('([﹒﹔﹖﹗．；。！？]["’”」』]{0,2}|：(?=["‘“「『]{1,2}|$))')
def splitsentence(sentence):
    '''Split a piece of Chinese into sentences.'''
    # s = ''.join((chr(ord(ch)+0xFEE0) if ch in halfwidth else ch) for ch in sentence)
    s = sentence
    slist = []
    for i in resentencesp.split(s):
        if resentencesp.match(i) and slist:
            slist[-1] += i
        elif i:
            slist.append(i)
    return slist
```

**Comment by windweller** [comment]
啊，这个方法明显好多了。。。我自己写了一个但是没有这个简洁。。

**Comment by silencecmsj** [comment]
引号里的多个句子按几个句子算？
