### ISSUE TITLE
自定义词典达到几十万词汇量，运行慢怎么办

### ISSUE THREAD

**Issue by grandmoi** [fxsjy/jieba#584]
我的自定义词典中有60多万的词汇，识别一个句子运行特别慢要将近1分钟，有什么解决办法吗，求各位大神解答，谢谢！

**Comment by 2276959997** [comment]
怎么解决的？

**Comment by grandmoi** [comment]
不会变慢的，我的程序写的有问题，后来用500多万词都没事

**Comment by sevillazh** [comment]
> 
> 
> 不会变慢的，我的程序写的有问题，后来用500多万词都没事

请问用什么方法得到的词典

**Comment by dygwyp** [comment]
> 不会变慢的，我的程序写的有问题，后来用500多万词都没事

请问你的词典文件多大？我也需要使用自定义词典，但是大小达到3.4g...

**Comment by CRX1024** [comment]
请问用什么方法得到的词典
