### ISSUE TITLE
Improve the word frequency but cannot get expected result

### ISSUE THREAD

**Issue by XinhongWu** [fxsjy/jieba#593]
I try to split sentence：
价格创新高的艺术品
the answer is ：
价格    | 创新  |  高    |   的   |艺术品
 Expected：
价格   |创    |新高      |    的       |艺术品
Then I find "创新" “新高” in the default dictionary：
新高 698 v
创新 4681 v

I modify ‘‘新高’’ from 698 to 7000,
but the result still not change.
Can you give me some advice?

**Comment by huangwei2013** [comment]
试下把“创”也设置一下呢

**Comment by XinhongWu** [comment]
@huangwei2013 尝试设置了创的词频，没有得到想要的结果。
代码中，使用的是动态规划的方式计算最大的概率组合，这种修改有点类似调优。
实测：暴力删除 创新这个词可以达到目标。

**Comment by XinhongWu** [comment]
通过设置 创新或者新高的词频，是可以达到效果的，目前已做1个工具，可以进行词频的建议。
