### ISSUE TITLE
带 “-”的英文自定义单词问题

### ISSUE THREAD

**Issue by zhyanlin** [fxsjy/jieba#626]
我自定义了一个词典，有一些包含“-”的词，比如 “SK-II”。加载这个词库时候发现只有这类词语没法生效，会被分为 SK，-，II,而不是SK-II。请问这个问题应该如何解决

**Comment by liuhyzhy0909** [comment]
同问，自定义词典中有5%,但分词会分开，词性标注的会分开 但正常分词不会被分开

**Comment by BaIGaO** [comment]
同问！
在自定义词典中定义带 “-” 的词或者调用add_word都不起作用

**Comment by BaIGaO** [comment]
找到解决方法了
修改jieba/__init__.py代码中的re_han_default 正则表达式为如下值：
`re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._%\-]+)", re.U)`

**Comment by guotong1988** [comment]
Can solve this: https://github.com/fxsjy/jieba/issues/692

**Comment by v-yunbin** [comment]
@BaIGaO NBA 依然被分成了 N B A
