### ISSUE TITLE
如何在项目中全局加载自定义词典

### ISSUE THREAD

**Issue by lpq29743** [fxsjy/jieba#636]
假设我有一个项目，包含文件 A 和 B，他们都需要加载同一个自定义词典。如果分别在两个文件中加载，则会比较耗时，有没有一种可以全局加载的方式

**Comment by botissue** [comment]
[HanLP](https://github.com/hankcs/HanLP)的自定义词典好像是全局的

**Comment by lpq29743** [comment]
我最后解决的方式是定义一个全局的 jieba 配置文件 jieba_config.py：
```
import jieba

jieba.load_userdict('dict.txt')
```
然后在需要使用的模块中执行`import jieba_config`：
```
import jieba
import jieba_config

print(jieba.lcut('李小福是创新办主任也是云计算方面的专家'))
```
