### ISSUE TITLE
中英混合词无法分词问题

### ISSUE THREAD

**Issue by FesonX** [fxsjy/jieba#642]
使用`jieba.set_dictionary('test.txt')`强制分词时发现全中文的天使轮,以及公司名可以直接识别出来, 无论关不关闭发现新词, 而中英混合的词加入字典后 **无论关不关闭分词都无法发现新词** ,如字典中的`pre-A轮`

分词的测试语句是
> `极客教育完成近千万元天使轮融资，由新东方领投`
> `星舆科技Starcart完成近亿元pre-A轮融资`
```
# test.txt
天使轮 50
A轮 5
Pre-A轮 90
A+轮 6
pre-A轮 90
B轮 50
B+轮 50
C轮 50
IPO 40
星舆科技 10
```

**Comment by Lyndon1994** [comment]
请问如何解决的？
