### ISSUE TITLE
Ruby 中调用jieba

### ISSUE THREAD

**Issue by yun-cn** [fxsjy/jieba#650]
我是使用 `PyCall::Import`然后调用python 的结巴 但是到了对象那一块的时候 就不知道怎么弄了

```
require 'pycall/import'
include PyCall::Import
pyimport :jieba
seg_list = jieba.cut_for_search("小明硕士毕业于中国科学院计算所，后在日本京都大学深造")
```
上面的seg_list生成一个对象,  ` <generator object Tokenizer.cut_for_search at 0x10ca046d0>`
怎么像是分词结果呢

**Comment by YSZYCF** [comment]
you can use this way. list(generator)

Joy_Zhang <notifications@github.com> 于2018年7月25日周三 上午7:19写道：

**Comment by gumblex** [comment]
用 lcut_for_search 直接生成列表

**Comment by yun313350095** [comment]
@gumblex   是在ruby环境下吗

**Comment by yun313350095** [comment]
@YSZYCF 
Can you give me an example?

**Comment by YSZYCF** [comment]
if use jieba on the windows, you can use this way.
word_seg =  jieba.cut_for_search("小明硕士毕业于中国科学院计算所，后在日本京都大学深造")
word-seg = list(word_seg)

Joy_Zhang <notifications@github.com> 于2018年7月25日周三 上午10:49写道：
