### ISSUE TITLE
使用用户字典不生效

### ISSUE THREAD

**Issue by zhanwen** [fxsjy/jieba#656]
使用jieba分词的时候，使用默认的分词模式，会将一句话中的“小区的外来人员激增”，将“外来人员”分在了一起。而我在自定义字典中添加了“外来人”，但是还是出现了“外来人员”，请问怎么修改，才可以将“外来人员”分成“外来人” “员”

**Comment by xwzhong** [comment]
原因应该是p(外来人员)>p(外来人)*p(员), 你试着将“外来人”的词频调高一点

**Comment by zhanwen** [comment]
调到2000都不行，这个试了

**Comment by qxde01** [comment]
能否加入对特殊符号分词支持呢，比如火星颜文字表情比如<(￣3￣)> ，这类字符在训练语料时是非常有用的

**Comment by xwzhong** [comment]
@zhanwen 你加到20w就可以了

**Comment by xwzhong** [comment]
@qxde01 这个得去改jieba内部的源码，它有默认切分的部分（通过规则确定）

**Comment by zhanwen** [comment]
@xwzhong  你试了？

**Comment by botissue** [comment]
[HanLP](https://github.com/hankcs/HanLP)可以：

```python
from pyhanlp import *

segment = HanLP.newSegment('感知机').enableCustomDictionaryForcing(True)
CustomDictionary.insert('外来人')
print(segment.seg("小区的外来人员激增"))
```

> [小区/n, 的/u, 外来人/n, 员/Ng, 激增/v]

**Comment by yangqingxin1123** [comment]
> [HanLP](https://github.com/hankcs/HanLP)可以：
> 
> ```python
> from pyhanlp import *
> 
> segment = HanLP.newSegment('感知机').enableCustomDictionaryForcing(True)
> CustomDictionary.insert('外来人')
> print(segment.seg("小区的外来人员激增"))
> ```
> 
> > [小区/n, 的/u, 外来人/n, 员/Ng, 激增/v]
**刚刚试的，好像不行。**
>>> from pyhanlp import *
>>> segment = HanLP.newSegment('感知机').enableCustomDictionaryForcing(True)
>>> CustomDictionary.insert('外来人')
True
>>> print(segment.seg("小区的外来人员激增"))
[小区/n, 的/u, 外来人员/n, 激增/v]

**Comment by MichaelCro** [comment]
# jieba==0.42.1

import jieba

jieba.add_word('外来人', freq=50000)
print(jieba.lcut('小区的外来人员激增'))

"""
Please say nothing
Just call me leifeng
"""
