### ISSUE TITLE
繁体 简体问题

### ISSUE THREAD

**Issue by piaolingxue** [fxsjy/jieba#67]
请问为什么不直接 将繁体统一转换成简体 ？ 这样字典就不用冗余存储同一词的简繁体了。

如果有需要繁体的场合，可以通过在api中放一个参数来控制是输出繁体还是简体？

现在 python 简繁体转换的库还是很多的
而且 中文全角半角最好也统一成半角好，分词的结果直接是转好的半角字符。

**Comment by hurryzeng** [comment]
可以提供个参数，默认兼容一起，就是仍然区分繁简
改这个参数可以分词结果统一使用简体或繁体... 给我们这些有需要的.... :)

**Comment by liutianling** [comment]
@fxsjy 谢谢您的工作和分享。非常认同您说的支持原生繁体，有些时候繁转简意思都不通。想问下您说的繁体词典在哪里，谢谢。
