### ISSUE TITLE
jieba 如何设定用户词典以屏蔽切割邮箱以及域名等

### ISSUE THREAD

**Issue by point6013** [fxsjy/jieba#677]
- 需要设定需要不须分割的邮箱以及域名

**Comment by gaozheng1982** [comment]
正则表达式判断





来自钉钉专属商务邮箱------------------------------------------------------------------
发件人：point6013<notifications@github.com>
日　期：2018年10月23日 12:06:52
收件人：fxsjy/jieba<jieba@noreply.github.com>
抄　送：Subscribed<subscribed@noreply.github.com>
主　题：[fxsjy/jieba] jieba 如何设定用户词典以屏蔽切割邮箱以及域名等 (#677)


需要设定需要不须分割的邮箱以及域名
