### ISSUE TITLE
Viterbi算法的初始状态计算是不是有错误？

### ISSUE THREAD

**Issue by KaiyuanGao** [fxsjy/jieba#683]
jieba的viterbi算法：
`def viterbi(obs, states, start_p, trans_p, emit_p):  
    V = [{}]  # tabular
    path = {}
    for y in states:  # init
        V[0][y] = start_p[y] + emit_p[y].get(obs[0], MIN_FLOAT)
        path[y] = [y]
`
这里面的 V[0][y] = start_p[y] + emit_p[y].get(obs[0], MIN_FLOAT)中间的加号是不是应该是乘号？
查阅了李航老师的小蓝书P185，初始化viterbi变量的时候是相乘的诶...

**Comment by fann1993814** [comment]
並沒有錯，取log後就變成相加
因為用prob計算會underflow
