### ISSUE TITLE
模型的数据是如何生成的？

### ISSUE THREAD

**Issue by mtejiang** [fxsjy/jieba#7]
就是finalseg/prob_*.py中的这些数据

**Comment by guzhenping** [comment]
有没有jieba分词和其他框架对比的测试？我很想知道结巴分词的排名~~

**Comment by sherlockzoom** [comment]
@fandywang 这个可以参考[清华大学中文分词](http://thulac.thunlp.org/#%E4%BB%A3%E8%A1%A8%E5%88%86%E8%AF%8D%E8%BD%AF%E4%BB%B6%E7%9A%84%E6%80%A7%E8%83%BD%E5%AF%B9%E6%AF%94)工具介绍部分

**Comment by chenjun0210** [comment]
您好，有对应的模型训练代码吗？这边想重新利用自己这边的语料训练一个HMM统计分词模型

**Comment by wangjiang0624** [comment]
您好，假设我使用了自定义词典，那么相应的HMM参数（初始状态概率、状态转移概率、观测概率）会不会被重新训练？

**Comment by Etc170322** [comment]
@fxsjy 请问能否训练模块posseg下的各个pro_文件？

**Comment by ICDI0906** [comment]
@fxsjy 请问一下，怎么使用预料来生成自定领域，比如: 新闻 领域 的词典啊？是用HMM 模型吗？

**Comment by zd06040224** [comment]
jieba中的hmm模型是否可以用自己的训练语料生成？

**Comment by CloudandML** [comment]
@fxsjy 我想请教一下，我对jieba/dict.txt文件进行了调整，另外我也自定义了词典、自定义调整分词、自定义删除，但是每次运行都需要先进行这些操作，否则并不起作用。问题是：我都已经删除了dict.txt中的词语了，为什么还是会分出那个词呢？另外，如何自己训练或修改模型？谢谢！

**Comment by zhaozk0745** [comment]
咨询个问题：我有些词语拆分，可能在默认词库里面存在，我在自定义词库里面对他进行单独的拆分以便于程序能够识别，但是发现效果不理想。举例：默认词库存着“非正常”这词语，实际上我需要程序能够识别出来并拆分为“非”+“正常”这种，我添加了自定义词典不能生效，只能把默认词库的“非正常”删除。因此咨询下默认词库和自定义词库的优先级谁的大？另外对自定义词典的词频理解不是很充分，词频的值是越大越优先识别么？

**Comment by zhaozk0745** [comment]
另外在默认词库里面单个汉字的词频定义都是很大的？这个定义数值取决于什么？

**Comment by crazyiori2003** [comment]
@fxsjy 您好，想请教一下，我想对着一篇论文分词，论文里本身就有关键词一栏，5个关键词用分号隔开的，这五个隔开的词里面如果不做设置，还会被分词吗，能怎么设置，让他看见某个符号分开的词不要去分他吗？

**Comment by yuzhengyao** [comment]
您好，我想问几个问题1、jieba分词的字典dict.txt是经过怎么处理得到的，是Python脚本处理得到的吗？那可是98年人民日报语料库最开始就是新闻，并没有进行分词，还是生语料库，从生语料库经过怎样的处理变成了网上公开的已经标注过的人民日报语料，是人工标注的吗？2、如果是人工标注的话，那现在假设已经得到了被人工标注好了的人民日报语料，里面是已经人工分好词并且词性标注好了的，那得到这个被标注好了的语料库，下一步经过怎样的处理得到jieba中的dict.txt的？如果是python脚本处理的话，是具体怎样处理的呢？

**Comment by shenfuli** [comment]
@fxsjy C++ 版本支持paddle 的那个模型吗

**Comment by pc123s** [comment]
@fxsjy  通过对jiebaHMM自定义字典发射字典的处理，以'B'来说，那么P[B|字]代表B状态下某个字的概率，按照统计规律来说，P(B)下所有字的概率只和应该为1，但是我将jieba的hmm中的prob_emit字典读取统计后，发现B下面所有字的概率和是大于1的。具体代码如下：
with open('./prob_emit_测试.py',mode='r',encoding='utf-8') as f:
    data=f.readlines()
str=''
for line in data:
    line1=line.strip()
    str+=line1
dict3=eval(str[2:])
n=0
for key,value in dict3['B'].items():
   n+=exp(value)
print('字典里面B所有字的概率合集为',n)

#结果
字典里面B所有字的概率合集为 1.3132772700102078

**Comment by leemoor** [comment]
> 咨询个问题：我有些词语拆分，可能在默认词库里面存在，我在自定义词库里面对他进行单独的拆分以便于程序能够识别，但是发现效果不理想。举例：默认词库存着“非正常”这词语，实际上我需要程序能够识别出来并拆分为“非”+“正常”这种，我添加了自定义词典不能生效，只能把默认词库的“非正常”删除。因此咨询下默认词库和自定义词库的优先级谁的大？另外对自定义词典的词频理解不是很充分，词频的值是越大越优先识别么？

找到答案了吗 我也有这个疑问呢

**Comment by zpppy** [comment]
> @fxsjy 通过对jiebaHMM自定义字典发射字典的处理，以'B'来说，那么P[B|字]代表B状态下某个字的概率，按照统计规律来说，P(B)下所有字的概率只和应该为1，但是我将jieba的hmm中的prob_emit字典读取统计后，发现B下面所有字的概率和是大于1的。具体代码如下：
> with open('./prob_emit_测试.py',mode='r',encoding='utf-8') as f:
> data=f.readlines()
> str=''
> for line in data:
> line1=line.strip()
> str+=line1
> dict3=eval(str[2:])
> n=0
> for key,value in dict3['B'].items():
> n+=exp(value)
> print('字典里面B所有字的概率合集为',n)
> 
> #结果
> 字典里面B所有字的概率合集为 1.3132772700102078

同问，为什么概率相加不为1。

**Comment by zpppy** [comment]
字典里面B所有字的概率和不为1，请问下是什么原因哈

**Comment by returnWOW** [comment]
> 字典里面B所有字的概率和不为1，请问下是什么原因哈

觉得应该是浮点数原因，比如一般1.0可能是一个趋近的数：0.9999999......

**Comment by datalee** [comment]
> 字典里面B所有字的概率和不为1，请问下是什么原因哈

而且我看都是负数，有什么考虑？

**Comment by tomnattle** [comment]
> 

我正在做类似的事情，我有70万数据，先统计单个文字，然后查看文字和其他文字出现的概率，出现在词头和词尾的概率，然后计划生成词典，跑起来速度比较慢，而且吃内存。

**Comment by yuzhengyao** [comment]
您好，谢谢您的关注，我将尽快查看!

**Comment by manother** [comment]
邮件已收到~

**Comment by jialexu** [comment]
> @fxsjy 通过对jiebaHMM自定义字典发射字典的处理，以'B'来说，那么P[B|字]代表B状态下某个字的概率，按照统计规律来说，P(B)下所有字的概率只和应该为1，但是我将jieba的hmm中的prob_emit字典读取统计后，发现B下面所有字的概率和是大于1的。具体代码如下： with open('./prob_emit_测试.py',mode='r',encoding='utf-8') as f: data=f.readlines() str='' for line in data: line1=line.strip() str+=line1 dict3=eval(str[2:]) n=0 for key,value in dict3['B'].items(): n+=exp(value) print('字典里面B所有字的概率合集为',n)
> 
> #结果 字典里面B所有字的概率合集为 1.3132772700102078

没有看过代码，不过我猜是解决类似统计概率中的0为分母的情况。

**Comment by yuzhengyao** [comment]
您好，谢谢您的关注，我将尽快查看!
