### ISSUE TITLE
怎么获得jieba的默认词表？只能打开dict.txt文件吗？或者有什么方式可以获得中文常用、高频词？

### ISSUE THREAD

**Issue by catqaq** [fxsjy/jieba#730]
求助：
jieba有一堆函数，但我找不到文档，也找不到获得词表的方式：
jieba.dt   #Tokenizer dictionary=None
jieba.dt.dictionary #NoneType
jieba.dt.total #60101967
type(jieba.dt.total) #int
type(jieba.iterkeys) #function
jieba.calc
jieba.get_dict_file
jieba.iteritems
jieba.xrange
type(jieba.DEFAULT_DICT)
。。。

**Comment by huangwei2013** [comment]
可参看 jieba/__init__.py 中 def add_word中的处理：
`    
   word = strdecode(word)
   ...
  self.FREQ[word] = freq
`

**Comment by catqaq** [comment]
ok, thanks for your reply.
