### ISSUE TITLE
How can I tokenize sentence from paragraph using jiebo?

### ISSUE THREAD

**Issue by oya163** [fxsjy/jieba#742]
I don't understand Chinese, but I am working on Chinese tokenization. I want to perform sentence segmentation. How can I do that with jieba?

**Comment by lumeng** [comment]
Have you tried the examples in the manual ?

**Comment by oya163** [comment]
Yes, I checked the examples. I think there is no example of segmenting a paragraph into sentences only? Like the one in nltk, span_tokenize() for sentences.

**Comment by ybkun** [comment]
> Yes, I checked the examples. I think there is no example of segmenting a paragraph into sentences only? Like the one in nltk, span_tokenize() for sentences.

I don't think you should jieba for such case.  Jieba is desined to segment sentence into words.
And I think you can easily use `punctuation mark`(for example: "。"， “！”, "？") to split paragraph into sentences

**Comment by oya163** [comment]
Yes, thank you @ybkun. I used regex to split paragraph into sentences.
This [post](https://stackoverflow.com/a/45274695/4595807) helped me.
