### ISSUE TITLE
为什么不能对jieba.cut()返回的generator进行迭代for循环

### ISSUE THREAD

**Issue by AndyPromise** [fxsjy/jieba#764]
# encoding=utf-8
import numpy as np
import re
import pandas as pd
import jieba

df = pd.read_excel('201208.xls', usecols=[21])
for item in df.values:
    print(item)
    seg_list = jieba.cut(item)
    print(seg_list.__class__)  #<class 'generator'>
    **for cut_item in seg_list:
        print(cut_item)**

C:\Users\liuya\Anaconda3\envs\dictionary\python.exe E:/PythonProgram/Dic/Dictionary.py
WARNING *** file size (5534334) not 512 + multiple of sector size (512)
['子宫前位，正常大，宫腔线清，内膜0.4cm，宫壁回声均匀。;双卵巢未显示，双附件区未及明显包块。;CDFI:未见异常。']
Traceback (most recent call last):
<class 'generator'>
  File "E:/PythonProgram/Dic/Dictionary.py", line 12, in <module>
    for cut_item in seg_list:
  File "C:\Users\liuya\Anaconda3\envs\dictionary\lib\site-packages\jieba\__init__.py", line 282, in cut
    sentence = strdecode(sentence)
  File "C:\Users\liuya\Anaconda3\envs\dictionary\lib\site-packages\jieba\_compat.py", line 37, in strdecode
    sentence = sentence.decode('utf-8')
AttributeError: 'numpy.ndarray' object has no attribute 'decode'

Process finished with exit code 1

**Comment by AndyPromise** [comment]
AttributeError: 'numpy.ndarray' object has no attribute 'decode'

**Comment by FeelCoolOne** [comment]
@AndyPromise jieba.cut输入的第一个参数必须是字符串，这里的item是numpy。ndarray类型的，导致类型匹配，需要做类型转换。

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html

**Comment by AndyPromise** [comment]
> @AndyPromise jieba.cut输入的第一个参数必须是字符串，这里的item是numpy。ndarray类型的，导致类型匹配，需要做类型转换。
> 
> https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html
感谢，已解决
