### ISSUE TITLE
用户自定义词典中的词如果包含下划线, 则该词仍然会被分开

### ISSUE THREAD

**Issue by lxw0109** [fxsjy/jieba#771]
用户词典如下:
```
免fei 1
娇喘 1
HIT_DATE 1
HIT_HMS 1
HIT_HERTZ_URL 1
```
首先用户词典确实生效了(使用自定义词典后`免fei`能够不被分开), 但是下面的`HIT_DATE`, `HIT_HMS`, `HIT_HERTZ_URL`无法被正确处理, 仍然会被分开
**请问如何使自定义词典中以下划线拼接的这些词能够不被分词器分开?**

感谢~

**Comment by DingHanyang** [comment]
你可以在 __init__.py里面找到一个正则叫做re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._%\-]+)", re.U)，简单来说，分词器会先切分句子，而这里把下划线当作了切分句子的一个分隔符。（好像全模式是可以切出下划线的）如果你需要切出下划线，可以尝试对这里进行修改

**Comment by lxw0109** [comment]
> 你可以在 **init**.py里面找到一个正则叫做re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&._%-]+)", re.U)，简单来说，分词器会先切分句子，而这里把下划线当作了切分句子的一个分隔符。（好像全模式是可以切出下划线的）如果你需要切出下划线，可以尝试对这里进行修改

感谢~
