### ISSUE TITLE
TypeError: cut() got an unexpected keyword argument 'use_paddle'

### ISSUE THREAD

**Issue by VXenomac** [fxsjy/jieba#792]
**问题**

jieba v0.40 以下无法使用 paddle 模式，文档中暂未说明使用 paddle 模式需要更新至最新版本

**运行环境（系统环境及 jieba 版本）**

系统环境：macOS Catalina 10.15.2
jieba 版本：0.3.9
python 版本：3.7.4

**代码及截图**

```
import jieba
seg_list = jieba.cut("我来到北京清华大学", use_paddle=True)
print("Paddle Mode: " + "/ ".join(seg_list))  # paddle模式
```

**错误信息**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cut() got an unexpected keyword argument 'use_paddle'
```
**解决方案**

```
pip install jieba --upgrade
```

**Comment by xyzhou-puck** [comment]
@JesseyXujin ，麻烦review并更新一下文档。

**Comment by JesseyXujin** [comment]
你好，文档里面做过说明了。请给出详细的复现步骤，比如通过pip源安装jieba还是python setup.py install 等。以便我们这边能更好的优化问题。谢谢反馈。

**Comment by JesseyXujin** [comment]
文档里说明的部分如下：
如果需要使用paddle模式下的分词和词性标注功能，请先安装paddlepaddle-tiny，pip install paddlepaddle-tiny==1.6.1。
