### ISSUE TITLE
新版本的切中英文混合的问题

### ISSUE THREAD

**Issue by wyb008** [fxsjy/jieba#810]
一直用的0.3.6，今天升级到最新版本，发现很多逻辑不一样，比如 “steel健身爆发力运动兴奋补充剂” 被切分为了如下的分词，"steel"不知道为什么丢了？
['s']
['健身']
['爆发']
['爆发力']
['运动']
['兴奋']
['补充']
['补充剂']

**Comment by fxsjy** [comment]
@wyb008 , 你是用的cut_all模式分词吗？这个bug是0.41版本引入的， 在今天最新发布的0.42版修复了。
