### ISSUE TITLE
AttributeError: module 'jieba' has no attribute 'enable_paddle'

### ISSUE THREAD

**Issue by ahbon123** [fxsjy/jieba#812]
请问已安装`paddlepaddle-tiny`，运行`jieba.enable_paddle()`还是报标题中的错误，咋解决呀？

**Comment by fxsjy** [comment]
pritn(jieba.__version__) 看看？ 把jieba版本升级到最新

**Comment by ahbon123** [comment]
升级后重启了电脑可以了，谢谢。
