### ISSUE TITLE
paddle模式报unix time的错误

### ISSUE THREAD

**Issue by xxxxzr** [fxsjy/jieba#831]
macOS Catalina 10.15.3 
version: 0.42.1             
python 3.7.4

使用paddle模式分词的时候，会报如下的错误

`W0320 16:18:13.683133 163794368 init.cc:205] *** Aborted at 1584692293 (unix time) try "date -d @1584692293" if you are using GNU date ***
W0320 16:18:13.683434 163794368 init.cc:205] PC: @                0x0 (unknown)
W0320 16:18:13.685402 163794368 init.cc:205] *** SIGFPE (@0x11f9648b8) received by PID 95931 (TID 0x109c34dc0) stack trace: ***
W0320 16:18:13.685555 163794368 init.cc:205]     @     0x7fff6d17b42d _sigtramp
W0320 16:18:13.687621 163794368 init.cc:205]     @        0x11f9648b9 paddle::operators::math::RowwiseAdd<>::operator()()
W0320 16:18:13.688290 163794368 init.cc:205]     @        0x11ea62a7d paddle::operators::GRUCPUKernel<>::BatchCompute()
W0320 16:18:13.688731 163794368 init.cc:205]     @        0x11ea62430 _ZNSt3__110__function6__funcIZNK6paddle9framework24OpKernelRegistrarFunctorINS2_8platform8CPUPlaceELb0ELm0EJNS2_9operators12GRUCPUKernelIfEENS8_IdEEEEclEPKcSD_iEUlRKNS3_16ExecutionContextEE_NS_9allocatorISH_EEFvSG_EEclESG_
W0320 16:18:13.689159 163794368 init.cc:205]     @        0x11f92f88c paddle::framework::OperatorWithKernel::RunImpl()
W0320 16:18:13.689570 163794368 init.cc:205]     @        0x11f92f5fe paddle::framework::OperatorWithKernel::RunImpl()
W0320 16:18:13.689980 163794368 init.cc:205]     @        0x11f92b15b paddle::framework::OperatorBase::Run()
W0320 16:18:13.690359 163794368 init.cc:205]     @        0x11e4c1f2e paddle::framework::Executor::RunPreparedContext()
W0320 16:18:13.690747 163794368 init.cc:205]     @        0x11e39e448 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL24pybind11_init_core_noavxERNS_6moduleEE5$_102vJRNS2_9framework8ExecutorEPNS7_22ExecutorPrepareContextEPNS7_5ScopeEbbbEJNS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE_8__invokeESU_
W0320 16:18:13.691113 163794368 init.cc:205]     @        0x11e318ee9 pybind11::cpp_function::dispatcher()
W0320 16:18:13.691382 163794368 init.cc:205]     @        0x1091c54e8 _PyMethodDef_RawFastCallKeywords
W0320 16:18:13.691496 163794368 init.cc:205]     @        0x1091c4fa0 _PyObject_FastCallKeywords
W0320 16:18:13.691748 163794368 init.cc:205]     @        0x109301d75 call_function
W0320 16:18:13.691879 163794368 init.cc:205]     @        0x1092fea83 _PyEval_EvalFrameDefault
W0320 16:18:13.692129 163794368 init.cc:205]     @        0x1092f334a _PyEval_EvalCodeWithName
W0320 16:18:13.692256 163794368 init.cc:205]     @        0x1091c5313 _PyFunction_FastCallKeywords
W0320 16:18:13.692507 163794368 init.cc:205]     @        0x109301c67 call_function
W0320 16:18:13.692637 163794368 init.cc:205]     @        0x1092ffa7e _PyEval_EvalFrameDefault
W0320 16:18:13.692896 163794368 init.cc:205]     @        0x1092f334a _PyEval_EvalCodeWithName
W0320 16:18:13.693023 163794368 init.cc:205]     @        0x1091c5313 _PyFunction_FastCallKeywords
W0320 16:18:13.693274 163794368 init.cc:205]     @        0x109301c67 call_function
W0320 16:18:13.693404 163794368 init.cc:205]     @        0x1092ffa7e _PyEval_EvalFrameDefault
W0320 16:18:13.693634 163794368 init.cc:205]     @        0x1092f334a _PyEval_EvalCodeWithName
W0320 16:18:13.693773 163794368 init.cc:205]     @        0x1091c5313 _PyFunction_FastCallKeywords
W0320 16:18:13.694023 163794368 init.cc:205]     @        0x109301c67 call_function
W0320 16:18:13.694154 163794368 init.cc:205]     @        0x1092ffa7e _PyEval_EvalFrameDefault
W0320 16:18:13.694399 163794368 init.cc:205]     @        0x1091c4be5 function_code_fastcall
W0320 16:18:13.694530 163794368 init.cc:205]     @        0x109301c67 call_function
W0320 16:18:13.694782 163794368 init.cc:205]     @        0x1092fea83 _PyEval_EvalFrameDefault
W0320 16:18:13.694926 163794368 init.cc:205]     @        0x1091dde19 gen_send_ex
W0320 16:18:13.695125 163794368 init.cc:205]     @        0x1092fec0a _PyEval_EvalFrameDefault
W0320 16:18:13.695250 163794368 init.cc:205]     @        0x1091c4be5 function_code_fastcall`

**Comment by xxxxzr** [comment]
分词代码
`    with open("xxx", "w+") as output:
        with open(path, 'r') as f:
            for line in f:
                split = line.replace("\n", "").split(",")
                workout = "%s:%s" % (split[0], split[1])
                content = process_content(split[2])
                if content is None or content is "":
                    continue
                print(content)
                content_array = pseg.cut(content, use_paddle=True)
`

**Comment by xxxxzr** [comment]
解决，分词文本里的空格和隐藏字符'\u3000'等导致

**Comment by hundanLi** [comment]
The same error, what's the problem?
