### ISSUE TITLE
在已有词典的情况下怎么让词性标注模块不切分词典中的词

### ISSUE THREAD

**Issue by liu0haha123** [fxsjy/jieba#876]
有某个专业领域的词典，但是这个专业领域词典中没有词性，需要根据这个专业领域词典对文字进行词性标注
但是在使用jieba.posseg进行词性标注时仍然会将词典的词切分为多个词，
例如“B-1-B轰炸机”会被切分为“B”+“-”+"1"+"-"+"B"+"轰炸机"
请问有对应的解决办法让jieba不对已有词典的词进行分词吗，词性标注不正确也可以

**Comment by lelechallc** [comment]
> 有某个专业领域的词典，但是这个专业领域词典中没有词性，需要根据这个专业领域词典对文字进行词性标注
> 但是在使用jieba.posseg进行词性标注时仍然会将词典的词切分为多个词，
> 例如“B-1-B轰炸机”会被切分为“B”+“-”+"1"+"-"+"B"+"轰炸机"
> 请问有对应的解决办法让jieba不对已有词典的词进行分词吗，词性标注不正确也可以

请问怎么解决的？
