### ISSUE TITLE
'·'总是被分开，无法保证英文名不被分割

### ISSUE THREAD

**Issue by xxupiano** [fxsjy/jieba#960]
比如
jieba.suggest_freq('理查德·凯利', True)
jieba.lcut('导演理查德·凯利却放弃了宣扬美国梦的乐观美好')
> ['导演', '理查德', '·', '凯利', '却', '放弃', '了', '宣扬', '美国', '梦', '的', '乐观', '美好']

**Comment by gesean** [comment]
这个要修改site-packages\jieba下init.py中几个正则表达式，来适配中文中间的特殊符号：　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 
1. 搜索 re_han_default = re.compile(“([\u4E00-\u9FD5a-zA-Z0-9+#&._]+)”, re.U)  改成 re_han_default = re.compile(“(.+)”, re.U) 
2. 搜索 re_userdict = re.compile(‘^(.+?)( [0-9]+)?( [a-z]+)?＄’, re.U) 改成 re_userdict = re.compile(‘^(.+?)(\u0040\u0040[0-9]+)?(\u0040\u0040[a-z]+)?$’, re.U) 

在词典中加入词，效果如下：
`import jieba
jieba.add_word('理查德·凯利')
jieba.lcut('导演理查德·凯利却放弃了宣扬美国梦的乐观美好')`

> ['导演', '理查德·凯利', '却', '放弃', '了', '宣扬', '美国', '梦', '的', '乐观', '美好']

**Comment by xxupiano** [comment]
感谢！
