### ISSUE TITLE
AttributeError: module 'jieba' has no attribute 'lcut'

### ISSUE THREAD

**Issue by tobylaifun** [fxsjy/jieba#979]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/60289741/197425044-388b3b83-482e-400e-a699-36f7b9aa0f31.png">
jieba: v0.42.1

经过测试，此问题仅在v0.42.1出现，在v0.42.0没有问题

请检查打包或是否删除了`lcut()`

**Comment by tobylaifun** [comment]
@fxsjy

**Comment by wqh17101** [comment]
![image](https://user-images.githubusercontent.com/26429138/211740475-74fdd915-7c9e-498b-a991-9eb86b432b97.png)
未出现该问题 @tobylai-toby

**Comment by tobylaifun** [comment]
@wqh17101 这个问题是我以前用3.7.4的时候有的，奇怪的是用3.9没有这个问题
