### ISSUE TITLE
大家散了吧！LLM的分词效果更好

### ISSUE THREAD

**Issue by 0xlength** [fxsjy/jieba#994]

**Comment by 0xlength** [comment]
而且有不少CPU就能正常运行的模型

**Comment by brynne8** [comment]
但是不够轻量。我要在1C1G的服务器上运行好多多东西呢。

**Comment by 0xlength** [comment]
> 但是不够轻量。我要在1C1G的服务器上运行好多多东西呢。

有256m or 512m 内存就能运行的轻量模型

**Comment by mdys** [comment]
@david0ffff  你好大佬 请问 LLM的分词 有具体的 github链接吗 谢谢
