### ISSUE TITLE
jieba.set_dictionary 给定的词性没有效果，统一变成了x

### ISSUE THREAD

**Issue by bitszhang** [fxsjy/jieba#998]
user_dict.txt 内容：

> 理想西溪金座 100 a
> 理想伊萨卡 100 a

另外还想问下，set_dictionary  的功能是替换默认字典，为什么我的字典只有2个词，会切出“哪个”，“位置”，“在”这些词呢？

![微信截图_20230811160509](https://github.com/fxsjy/jieba/assets/12874343/2e290971-6540-4c5d-9900-bf045f767b66)

**Comment by bitszhang** [comment]
已解决，使用如下方式
```
jieba.posseg.initialize("user_dict.txt")  # 手动初始化（可选）

sentence = '理想西溪金座在哪个位置。'

for pair in jieba.posseg.cut(sentence):
    print(pair)
```

**Comment by ringge** [comment]
> 已解决，使用如下方式
> 
> ```
> jieba.posseg.initialize("user_dict.txt")  # 手动初始化（可选）
> 
> sentence = '理想西溪金座在哪个位置。'
> 
> for pair in jieba.posseg.cut(sentence):
>     print(pair)
> ```

如果兩種user_dict和default_dict(jieba原來提供得)都使用可以嗎？我沒找到方法，因為jieba.posseg.initialize()只能加載一個辭典
